config/routes.rb
Rails.application.routes.draw do

  resources :uploaded_files, only: [:index, :new, :create, :destroy]
  root 'uploaded_files#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/uploaded_file.rb
class UploadedFile < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/uploaded_files_controller.rb
class UploadedFilesController < ApplicationController
  def index
    @uploaded_files = UploadedFile.all
  end

  def new
    @uploaded_file = UploadedFile.new
  end

  def create
    @uploaded_file = UploadedFile.new(uploaded_file_params)

    if @uploaded_file.save
      @uploaded_file.update(name: @uploaded_file.attachment.identifier,
                            path: @uploaded_file.attachment.url)

      Hutch.connect
      Hutch.publish('routing.key', subject: 'payment', action: 'received')

      redirect_to uploaded_files_path, notice: "The file #{@uploaded_file.name} has been uploaded."
    else
      render 'new'
    end
  end

  def destroy
    @uploaded_file = UploadedFile.find(params[:id])
    @uploaded_file.destroy

    redirect_to uploaded_files_path, notice: "The file #{@uploaded_file.name} has been deleted."
  end

  private

  def uploaded_file_params
    params.require(:uploaded_file).permit(:attachment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title My App
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags

  body
    .body-container
      = yield

app/views/uploaded_files/index.html.slim
h1 Upload Files

- if flash[:notice].present?
  .alert
    = flash[:notice]

= link_to 'New File', new_uploaded_file_path

ul
  - @uploaded_files.each do |uploaded_file|
    li
      .name = uploaded_file.name
      .url = link_to 'Download', uploaded_file.attachment_url
      .delete = button_to 'Delete', uploaded_file, method: :delete

app/views/uploaded_files/new.html.slim
h1 Upload a file

- if @uploaded_file.present?
  ul
    - @uploaded_file.errors.full_messages.each do |msg|
        li = msg

= form_for @uploaded_file, html: {multipart: true} do |f|
  = f.label :attachment
  = f.file_field :attachment
  = f.submit 'Save'